import Link from 'next/link';

const demos=[['موقع راس البر','https://rasalbar.egarat.online'],['نسخة العرض الأساسية','https://sakan-egy.vercel.app'],['مثال عقاري','https://akar-egy.vercel.app']];

function Dashboard(){return <div className="saas-dashboard"><div className="dash-bar"><span/> <span/> <span/><b>لوحة تحكم المكتب</b><em>● متصل</em></div><div className="dash-main"><aside><strong>س</strong><i>نظرة عامة</i><i>الحجوزات</i><i>العقارات</i><i>التقويم</i><i>الإعدادات</i></aside><section><header><div><small>أهلاً بك</small><h3>مكتبك العقاري</h3></div><button>+ إضافة عقار</button></header><div className="dash-stats"><div><small>حجوزات اليوم</small><b>12</b><em>+18%</em></div><div><small>المتاح الآن</small><b>28</b><em>عقار</em></div><div><small>العربون المحصل</small><b>8,450</b><em>ج.م</em></div></div><div className="dash-list"><b>آخر الحجوزات</b><p><span>م</span><label><b>محمد أحمد</b><small>شاليه الساحل · 12 - 15 أكتوبر</small></label><mark>قيد الانتظار</mark></p><p><span>س</span><label><b>سارة محمود</b><small>شقة المعادي · 18 - 20 أكتوبر</small></label><mark>مؤكد</mark></p><p><span>أ</span><label><b>أحمد علي</b><small>فيلا أكتوبر · 21 - 25 أكتوبر</small></label><mark>عربون مدفوع</mark></p></div></section></div></div>}

function Site(){return <div className="site-mock"><div className="browser"><span/> <span/> <span/><small>office.egarat.online</small></div><div className="mock-cover"><b>مكتبك العقاري</b><div><h3>احجز إقامتك</h3><p>شقق وشاليهات باسم مكتبك</p><button>استعرض العقارات</button></div></div><div className="mock-products"><i/><i/><i/></div></div>}

export default function SaaSLanding(){return <main className="saas-page">
<nav className="saas-nav"><div className="saas-container nav-inner"><Link href="/" className="saas-brand"><span>س</span><b>سكن</b><small>Rental SaaS</small></Link><div className="nav-links"><a href="#features">المميزات</a><a href="#how">كيف يعمل؟</a><a href="#pricing">الأسعار</a><a href="#demos">جرب النظام</a></div><a className="nav-cta" href="https://wa.me/201026569682?text=%D8%A7%D8%A8%D8%B9%D8%AA%20%D8%B3%D9%83%D9%86">ابدأ الآن</a></div></nav>
<section className="saas-hero"><div className="saas-container hero-grid"><div className="hero-copy"><span className="eyebrow">منصة SaaS مصرية متخصصة في التأجير</span><h1>استلم <b>موقعك</b><br/>قبل ما تدفع.</h1><p>موقع حجز احترافي للشقق والشاليهات باسم مكتبك، مع لوحة تحكم خاصة وإدارة الحجوزات والدفع والتوافر من مكان واحد.</p><div className="hero-actions"><a className="primary-btn" href="https://wa.me/201026569682?text=%D8%A7%D8%A8%D8%B9%D8%AA%20%D8%B3%D9%83%D9%86">ابعت «سكن» على واتساب ↗</a><a className="secondary-btn" href="#demos">شوف النظام شغال</a></div><div className="hero-trust">✓ بدون تكلفة إنشاء　 ✓ استلام خلال دقائق　 ✓ باسم مكتبك ورابطك</div></div><div className="hero-visual"><Site/><div className="float-card"><b>حجز جديد ✓</b><small>العربون تم استلامه</small></div></div></div></section>
<section className="proof-strip"><div className="saas-container proof-inner"><b>مصمم للسماسرة ومكاتب العقارات وأصحاب الشقق والشاليهات</b><span>موقع + لوحة تحكم + حجوزات + دفع</span><span>كل شيء باسمك</span></div></section>
<section id="features" className="saas-section"><div className="saas-container"><div className="section-head"><span>لماذا سكن؟</span><h2>مش مجرد موقع.<br/><b>ده نظام تأجير كامل باسمك.</b></h2><p>بدل ما كل حجز يبدأ برسالة واتساب، خلي العميل يشوف المتاح ويحجز ويدفع العربون، والحجز يدخل عندك مباشرة.</p></div><div className="feature-grid">{[['01','موقع باسم مكتبك','اسم المكتب والهوية والصور والعقارات في واجهة احترافية ورابط خاص.'],['02','لوحة تحكم خاصة','أضف العقارات والأسعار والصور وتابع الحجوزات من مكان واحد.'],['03','العربون أونلاين','استقبل العربون عبر InstaPay أو Vodafone Cash باستخدام رقمك.'],['04','التقويم يغلق تلقائياً','عند تأكيد الحجز تتحدث حالة العقار ويظهر المتاح والمحجوز.'],['05','الحجز يصل إليك','كل طلب حجز منظم داخل لوحة الإدارة بدلاً من عشرات الرسائل.'],['06','جاهز بدون وجع دماغ','لا استضافة ولا برمجة ولا إعدادات معقدة.']].map(x=><article key={x[0]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
<section id="how" className="saas-section how-section"><div className="saas-container"><div className="section-head centered"><span>من أول رسالة لأول حجز</span><h2>ثلاث خطوات فقط</h2></div><div className="steps">{[['01','ابعت «سكن»','تواصل معنا على واتساب ونعرفك بالنظام ونجهز بيانات مكتبك.'],['02','شوف موقعك','تستلم نسخة باسمك وتجرب الحجز ولوحة التحكم قبل الدفع.'],['03','ابدأ استقبال الحجوزات','رابطك يصبح جاهزاً وتبدأ استقبال العملاء والحجوزات مباشرة.']].map(x=><div key={x[0]}><strong>{x[0]}</strong><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div></div></section>
<section className="saas-section showcase"><div className="saas-container showcase-grid"><div><span className="section-kicker">لوحة الإدارة</span><h2>كل مكتب له<br/><b>لوحته الخاصة.</b></h2><p>الحجوزات والعقارات والتوافر والمدفوعات في واجهة بسيطة للاستخدام اليومي.</p><ul><li>إضافة وتعديل العقارات والصور والأسعار</li><li>متابعة الحجوزات وحالة كل طلب</li><li>تقويم واضح للمحجوز والمتاح</li><li>حساب خاص وكلمة مرور تختارها</li></ul></div><Dashboard/></div></section>
<section id="demos" className="saas-section"><div className="saas-container"><div className="section-head centered"><span>شوفه بنفسك</span><h2>مواقع شغالة بالفعل</h2><p>ادخل وجرب تجربة العميل بنفسك.</p></div><div className="demo-grid">{demos.map(d=><a key={d[1]} href={d[1]} target="_blank" rel="noreferrer" className="demo-card"><div className="demo-window">↗</div><small>موقع تجريبي</small><h3>{d[0]}</h3><span>فتح الموقع ←</span></a>)}</div></div></section>
<section id="pricing" className="saas-section pricing-section"><div className="saas-container pricing-wrap"><div><span className="section-kicker">بسيط وواضح</span><h2>من <b>10 جنيه</b><br/>في اليوم.</h2><p>الاشتراك الشهري <strong>300 جنيه</strong>، والاشتراك السنوي عليه خصم.</p><div className="launch"><b>عرض الإطلاق</b><span>أول 10 مواقع بسعر 300 جنيه شهرياً</span></div></div><div className="price-card"><span>اشتراك الموقع</span><div><strong>300</strong><small>ج.م / شهر</small></div><ul><li>✓ موقع باسم مكتبك</li><li>✓ رابط خاص</li><li>✓ لوحة تحكم خاصة</li><li>✓ إدارة العقارات والحجوزات</li><li>✓ InstaPay و Vodafone Cash</li><li>✓ تقويم التوافر</li></ul><a href="https://wa.me/201026569682?text=%D8%A7%D8%A8%D8%B9%D8%AA%20%D8%B3%D9%83%D9%86" className="primary-btn">ابدأ بتجربة موقعك</a><small>شوف النظام الأول. القرار بعد التجربة.</small></div></div></section>
<section className="faq-section saas-section"><div className="saas-container"><div className="section-head centered"><span>أسئلة سريعة</span><h2>قبل ما تبدأ</h2></div><div className="faq-grid"><details open><summary>هل أدفع قبل ما أشوف الموقع؟</summary><p>لا. تشوف موقعك وتجربه قبل الدفع.</p></details><details><summary>هل الموقع يكون باسم المكتب؟</summary><p>نعم، بالاسم والهوية والبيانات الخاصة بمكتبك مع رابط خاص.</p></details><details><summary>هل أضيف العقارات بنفسي؟</summary><p>نعم، من لوحة الإدارة الخاصة بك.</p></details><details><summary>هل العميل يحتاج واتساب؟</summary><p>لا. العميل يستطيع الحجز من الموقع مباشرة، ويظهر الطلب لديك في لوحة التحكم.</p></details></div></div></section>
<section className="final-cta"><div className="saas-container"><div className="final-box"><span>جاهز تشوفه؟</span><h2>ابعت <b>«سكن»</b> وخد موقعك للتجربة.</h2><p>01026569682</p><a href="https://wa.me/201026569682?text=%D8%A7%D8%A8%D8%B9%D8%AA%20%D8%B3%D9%83%D9%86" className="primary-btn">تواصل على واتساب ↗</a></div></div></section>
<footer className="saas-footer"><div className="saas-container footer-inner"><div><div className="saas-brand"><span>س</span><b>سكن</b><small>Rental SaaS</small></div><p>منصة مصرية متخصصة في أنظمة التأجير والحجز.</p></div><div><b>المنصة</b><a href="#features">المميزات</a><a href="#demos">التجارب</a><a href="#pricing">الأسعار</a></div><div><b>تواصل</b><a href="https://wa.me/201026569682?text=%D8%A7%D8%A8%D8%B9%D8%AA%20%D8%B3%D9%83%D9%86">واتساب 01026569682</a></div></div><div className="saas-container footer-bottom">© 2026 سكن — نظام تأجير عقاري جاهز باسمك</div></footer>
</main>}